import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { UsernameProvider } from '../contexts/UsernameContext';
import { SocketProvider } from '@/contexts/SocketContext';
import { LogProvider } from '@/contexts/LogContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'one-yeah',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <SocketProvider>
    <UsernameProvider>
    <LogProvider>
      <html lang="en">
      <body
        className={`${inter.className} min-h-screen bg-cover p-2`}
        style={{ backgroundImage: 'url("/assets/bg1.gif")' }}
      >{children}</body>
      </html>
    </LogProvider>
    </UsernameProvider>
    </SocketProvider>
  )
}
